(require 'color-theme)
;;;###autoload
(defun color-theme-tg ()
  "Color theme by Iain Wood, created 2011-04-22."
  (interactive)
  (color-theme-install
   '(color-theme-tg
     ((background-mode . light)
      (cursor-color . "grey")
      (foreground-color . "Black"))
     (hl-line((t (:background "#a0b4a0"))))
     (region ((t (:background "#a2b6a2"))))
     (rainbow-delimiters-\#7f7f7f-face ((t (:foreground "#7f7f7f" :weight extrabold))))
     (rainbow-delimiters-dark\ gray-face ((t (:foreground "dark gray" :weight extrabold))))
     (rainbow-delimiters-gold-face ((t (:foreground "gold" :weight extrabold))))
     (rainbow-delimiters-green-face ((t (:foreground "green" :weight extrabold))))
     (rainbow-delimiters-light\ blue-face ((t (:foreground "light blue" :weight extrabold))))
     (rainbow-delimiters-light\ gray-face ((t (:foreground "light gray" :weight extrabold))))
     (rainbow-delimiters-orange-face ((t (:foreground "orange" :weight extrabold))))
     (rainbow-delimiters-slate\ blue-face ((t (:foreground "slate blue" :weight extrabold))))
     (rainbow-delimiters-turquoise-face ((t (:foreground "turquoise" :weight extrabold))))
     (rainbow-delimiters-yellow-face ((t (:foreground "yellow" :weight extrabold))))
     (rainbow-paren-dark\ green-face ((t (:foreground "dark green" :weight extrabold))))
     (rainbow-paren-dark\ red-face ((t (:foreground "dark red" :weight extrabold))))
     (rainbow-paren-deep\ pink-face ((t (:foreground "deep pink" :weight extrabold))))
     (rainbow-paren-gold-face ((t (:foreground "gold" :weight extrabold))))
     (rainbow-paren-green-face ((t (:foreground "green" :weight extrabold))))
     (rainbow-paren-light\ blue-face ((t (:foreground "light blue" :weight extrabold))))
     (rainbow-paren-light\ gray-face ((t (:foreground "light gray" :weight extrabold))))
     (rainbow-paren-orange-face ((t (:foreground "orange" :weight extrabold))))
     (rainbow-paren-slate\ blue-face ((t (:foreground "slate blue" :weight extrabold))))
     (rainbow-paren-turquoise-face ((t (:foreground "turquoise" :weight extrabold))))
     (rainbow-paren-yellow-face ((t (:foreground "yellow" :weight extrabold))))
)))

